apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  webapp
  template:
    metadata:
      labels:
        app:  webapp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  webapp
        image: cdpipe.jfrog.io/cdpipe-docker/webapp:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080